AWSTemplateFormatVersion: "2010-09-09"
Description: 'Bucket to hold lambda function'

Resources:
  LambdaFunctionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-lambda-function'
